### ISSUE TITLE
Código limpio, ordenado y elegante. 

### ISSUE THREAD

**Issue by vicenlu** [alexcumplido/sprint5#2]
Muy buena primera impresión. Fácil lectura. 

He visto que en los curly braces de las arrow functions, pones un espacio previo, en cambio en los ifs no. Personalmente siempre pondría el espacio previo. Es un detalle menor.

https://github.com/alexcumplido/sprint5/blob/8af3eae53e8cb6c501fd02d127f6485c672e3a65/src/app.ts#L80

**Comment by alexcumplido** [comment]
Perfecto Luis, gracias por el comentario, justo ya lo he modificado, además era una de las cosas de formato en las que dudaba sobre duando ponerlo y cuando no, arreglado!
